version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - AIPROXY_TOKEN=${AIPROXY_TOKEN}
    command: >
      bash -c "pip install httpie && 
      uvicorn main:app --host 0.0.0.0 --port 8000"